const mock = [
  {
    category: "gorras",
    id: 1,
    title: "Gorra",
    Image: "gorra1.jpg",
    size: "M",
    price: 1500,
    stockMax: 5,
  },
  {
    category: "gorras",
    id: 2,
    title: "Gorra",
    Image: "gorra2.jpg",
    size: "XL",
    price: 1000,
    stockMax: 5,
  },
  {
    category: "gorras",
    id: 3,
    title: "Gorra",
    Image: "gorra3.jpg",
    size: "X",
    price: 1300,
    stockMax: 5,
  },
  {
    category: "gorras",
    id: 4,
    title: "Gorra",
    Image: "gorra4.jpg",
    size: "S",
    price: 1200,
    stockMax: 5,
  },
  {
    category: "remeras",
    id: 5,
    title: "Remera",
    Image: "remera1.jpg",
    size: "X",
    price: 2800,
    stockMax: 5,
  },
  {
    category: "remeras",
    id: 6,
    title: "Remera",
    Image: "remera2.jpg",
    size: "M",
    price: 2600,
    stockMax: 5,
  },
  {
    category: "remeras",
    id: 7,
    title: "Remera",
    Image: "remera3.jpg",
    size: "XL",
    price: 3500,
    stockMax: 5,
  },
  {
    category: "remeras",
    id: 8,
    title: "Remera",
    Image: "remera4.jpg",
    size: "S",
    price: 2300,
    stockMax: 5,
  },
];

export default mock;
